"""removed task

Revision ID: 5a998d281638
Revises: 62670c8337cd
Create Date: 2020-11-09 22:50:40.266802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a998d281638'
down_revision = '62670c8337cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'task')
    sa.Column('id', sa.Integer(), nullable=False)
    sa.Column('name', sa.String(100), nullable=True), 
    sa.Column(sa.String(100), nullable=True)
    sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('task', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
